apiVersion: apps/v1
kind: Deployment
metadata:
  name: krato-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krato-postgresql
  template:
    metadata:
      labels:
        app: krato-postgresql
    spec:
      containers:
        - name: krato-postgresql
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: 'Krato'
            - name: POSTGRES_PASSWORD
              value: '' # Note: It's highly recommended to use Kubernetes Secrets for passwords
            - name: POSTGRES_HOST_AUTH_METHOD
              value: 'trust'
